\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename mockgals.info
@settitle mockgals 0.1
@afourpaper
@c %**end of header





@copying
This manual is for @code{mockgals}, a program to make mock
astronomical objects in a FITS image and add the appropriate noise.

@comment Work on the software began on this from October 2013, but the
@comment manual was written in 2014.
Copyright @copyright{} 2013, 2014 Mohammad Akhlaghi.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts, and with no Back-Cover
Texts.  A copy of the license is available online at
@uref{http://www.gnu.org/copyleft/fdl.html, GNU FDL webpage}.
@end quotation
@end copying





@titlepage
@title MockGals
@subtitle Make mock stars and galaxies in a FITS image with noise.
@subtitle Manual for version 0.1.
@author Mohammad Akhlaghi

@page 
@vskip 0pt plus 1filll
@insertcopying

@ifplaintext
@insertcopying
@end ifplaintext
@end titlepage





@contents






@ifnottex
@node Top, QuickStart, (dir), (dir)
@top Short mockgals

This manual is for @code{mockgals}, which is a tool to create mock
galaxies and stars in an image and save the result in a FITS file.
@end ifnottex





@menu
* QuickStart::
* Introduction.::
* Installing::
* Configuring::
* MockParams::
* HowItWorks::
@end menu








@node QuickStart, Introduction., Top, Top
@chapter Quick start

Once @code{mockgals} is installed, if you simply run @code{./mockgals}
in the installed directory, 45 mock galaxies and 5 stars will be
randomly positioned in a @code{FITS} image of size @math{200*200}.




















@node Introduction., Installing, QuickStart, Top
@chapter An introduction.

Making mock galaxies is very important in the process of understanding
our data. @code{mockgals} was initially made with this exact
intent. Certain astronomical targets, for example elliptical
galaxies, are very sharp in their central regions, this makes a simple
calculation of the profile in the center of each pixel unrealistic for
such cases. The main advantage of @code{mockgals} is that it
integrates the central parts of profiles until a given accuracy. It
does this without any sorting or ordering and in a very fast manner.

@noindent
A summary of the advantages of @code{mockgals} includes:
@enumerate
@item
Integration of the center of the profile.
@item 
Very efficient in CPU usage, resuling in a very fast processing.
@item
Written in the C programming language, which is easy to understand
and modify or contribute to by any interested user.
@item
[To be added] Can make profiles in any dimentions. 
@end enumerate




















@node Installing, Configuring, Introduction., Top
@chapter Installation
@code{mockgals} relys on only 3 packages: @code{GSL} (for mathematical
functions), @code{FFTW} (for convolution) and @code{cfitsio} (for reading to and from FITS files).




















@node Configuring, MockParams, Installing, Top
@chapter Configuring mockgals.
Currently configuration paramters into @code{mockgals} can only be
given through single letter commandline options. The options are
explained below.




















@node MockParams, HowItWorks, Configuring, Top
@chapter Mock paramters
The parameters of the profiles you want to build into a FITS image are
fed to it though a table. In this section we will review how
@code{mockgals} reads that table and how best to prepare it.




















@node HowItWorks,  , MockParams, Top
@chapter How mockgals works
In this section we will give a complete review on how @code{mockgals}
works and how this is implemented in its coding in order to facilitate
your reading of the code and possibly modifying it and making it better.







@bye
